# Basic
title: TimeCostçš„åšå®¢
subtitle: çˆ±ä¸–ç•Œ - çˆ±å›½å®¶ - çˆ±äººæ°‘
KeyWords: TimeCostçš„åšå®¢ å¤©ä¸‹ äººç”Ÿ
description: äº¤æµQQç¾¤ï¼šæš‚æ—  
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: QuickSand
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS & Swift
url: "https://avatars.githubusercontent.com/u/82870005?v=4"

# Comment
comment:
    disqus: Time-Cost-QuickSand-de-bo-ke
    # duoshuo: xiaohange 
    # yungentie: http://noneless.tk

# Social
social:
    weibo: TimeCost
    github: TimeCost
    # twitter: 
    mail: xinhuodeai@163.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
# baidu:
#     id: b2e5ebc1a7bd53eca8c179a4864b3723

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-94074611-1  
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/xiaohange/xiaohange.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢
    description: è®¿é—®åšå®¢

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


